### ISSUE TITLE
Фикс проверки на TD/TK

### ISSUE THREAD

**Issue by SadWaifu** [serfreeman1337/csstatsx-sql#13]
Старая версия функции, которая выполняла проверку неверно, и, в последствии, не сохраняло данные в колонки с Team Kill и Team Damage:
```
is_tk(killer,victim)
{
	if(killer == victim)
		return true	
	
	return false
}
```

Новый вариант:
```
is_tk(killer,victim)
{
#if !defined REAPI
	if(pev(killer, pev_team) == pev(victim, pev_team))
#else
	if(get_member(killer, m_iTeam) == get_member(victim, m_iTeam))
#endif
		return true	
	
	return false
}
```

**Comment by serfreeman1337** [comment]
зато не было проблем с FFA режимом ✓

вот так сделано в CSX:
https://github.com/alliedmodders/amxmodx/blob/0bd69445f95f50768a7655eb06a78207b39eed98/modules/cstrike/csx/usermsg.cpp#L150

может быть, просто [get_user_team](https://github.com/alliedmodders/amxmodx/blob/0bd69445f95f50768a7655eb06a78207b39eed98/amxmodx/amxmodx.cpp#L1252) ?

и это issues, а не pull requests

**Comment by SadWaifu** [comment]
> зато не было проблем с FFA режимом ✓

Возможно, стоит сделать квар, мол для FFA или нет.

> может быть, просто [get_user_team](https://github.com/alliedmodders/amxmodx/blob/0bd69445f95f50768a7655eb06a78207b39eed98/amxmodx/amxmodx.cpp#L1252) ?

Роли не играет.

> и это issues, а не pull requests

Я знаю.

**Comment by serfreeman1337** [comment]
> Возможно, стоит сделать квар, мол для FFA или нет.

Или добавить проверку FFA кваров, при наличии csdm или/и regamedll
о, а на AMXX 1.9.0 это еще можно и [оптимизировать](https://github.com/serfreeman1337/csstatsx-sql/blob/71b51d286ff14796b6af3fd7a36f7319896d5ca4/scripting/csstatsx_sql.sma#L577)

> Роли не играет.

сейчас бы использовать pev... [ну ладно](https://github.com/serfreeman1337/csstatsx-sql/blob/71b51d286ff14796b6af3fd7a36f7319896d5ca4/scripting/csstatsx_sql.sma#L1751)

> Я знаю.

forever issue

**Comment by SadWaifu** [comment]
Ну, в общем, пищу для размышлений я донес. Дальше дело за Вами)
