### ISSUE TITLE
get_stats2_sql() returns wrong SteamID and wrong stats2 values

### ISSUE THREAD

**Issue by regener** [serfreeman1337/csstatsx-sql#16]
As the title says, try the following code:

```
new stats2[4], wSteamid[32], gSteamid[32];
get_stats2_sql(id, stats2, wSteamid, 31);
get_user_authid(id, gSteamid, 31);
client_print(id, print_chat, "get_stats2_sql: %s | get_user_authid: %s",wSteamid, gSteamid);
```

This will result in different SteamID-s printed out. (masked example)
> get_stats2_sql: STEAM_0:1:XXXXXX | get_user_authid: STEAM_0:1:YYYYYYY

For the reason above any values returned by stats2 are wrong.
In the database I have set 50 bombdef and 50 bombdefuse and 4 bombplants, but it returns 38 bombdefuse and 8 bombplants what exatly match an other line (other player) in the database.

**Comment by serfreeman1337** [comment]
**get_stats2_sql** is using for retrieving stats2 for given rank index (not for player index).
It works similar to get_stats native.

**Comment by regener** [comment]
Okay, that's new.

So how can I retrieve the correct values based on player index then?

**Comment by serfreeman1337** [comment]
Use **get_user_*** natives for player index.
**get_user_stats2_sql** for stats2.

**Comment by regener** [comment]
I feel kinda dumb now :D 
Thank you.

I think you should update the csstatx_sql.inc, because the plugin has 49 registered native while the inc has only 31.
Actually even the get_user_stats2 is missing and there is no _sql version of that.
