### ISSUE TITLE
Просьба

### ISSUE THREAD

**Issue by velesgs** [serfreeman1337/csstatsx-sql#2]
Вынесите пожалуйста настройки базы в конфиг, надаело каждый раз в исходник писать)))

**Comment by serfreeman1337** [comment]
В 0.7.1 вроде исправил загрузку кваров с amxx.cfg .

**Comment by velesgs** [comment]
Т.е. можно в amxx.cfg квары вынести?

**Comment by serfreeman1337** [comment]
Скорее всего хД
не проверял

**Comment by velesgs** [comment]
Хорошо проверим)

**Comment by patrig** [comment]
**public OnConfigsExecuted()** = не прокатывает на 1.8.3, просто прекратились записи в БД ...
Заменил назад на: **public plugin_cfg()** = Все стало нормально.

**Comment by serfreeman1337** [comment]
@patrig, а билд 1.8.3 какой? (**amxx version**)
Эти форварды появились [20 июля 2015 года](https://github.com/alliedmodders/amxmodx/commit/1f3c7cf272542a01ba3e4131c676a49be1f7aaf1).

**Comment by patrig** [comment]
@serfreeman1337, билд последний:
AMX Mod X version 1.8.3-dev+5066

**Comment by serfreeman1337** [comment]
@patrig, проверил, форвард вызывается аж спустя 5 секунд, после загрузки карты.
```
L 06/27/2016 - 14:13:04: -------- Mapchange to de_inferno --------
L 06/27/2016 - 14:13:10: [csstatsx_sql.amxx] --> OnConfigsExecuted call
```
Заменю на [OnAutoConfigsBuffered](https://github.com/alliedmodders/amxmodx/blob/861011fa24f893445a31b3a19b495cbb40724639/plugins/include/amxmodx.inc#L3266).

**Comment by patrig** [comment]
@serfreeman1337, да с данным форфардом все работает. Спасибо.
Еще дополнительный вопрос / проблема = которая не относится к данной ...

Не могу импортировать **csstats_maps.sql**

`SQL запрос:

DELIMITER ;
Ответ MySQL: Документация

#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'DELIMITER' at line 1`

**Comment by sashork** [comment]
Привет, слушай у меня вот этот плагин не работает с AES csstatsx_playtime_awards . Я там одну строчку заменил, что бы не по времени, а по скилу бралось. А у меня выходит что не понятно как он теперь работает. Можешь помочь в этом. Просто по времени это как то не так.
