### ISSUE TITLE
Проблемка с csstatsx_playtime_awards

### ISSUE THREAD

**Issue by sashork** [serfreeman1337/csstatsx-sql#3]
Привет, слушай у меня вот этот плагин не работает с AES csstatsx_playtime_awards . Я там одну строчку заменил, что бы не по времени, а по скилу бралось. А у меня выходит что не понятно как он теперь работает. Можешь помочь в этом. Просто по времени это как то не так.

**Comment by serfreeman1337** [comment]
Причем тут AES? Покажи что ты сделал, скопируй весь код.

> Просто по времени это как то не так. 

Так-то название плагина "награды за проведенное время на сервере".

**Comment by sashork** [comment]
[csstatsx_playtime_awards.txt](https://github.com/serfreeman1337/csstatsx-sql/files/341131/csstatsx_playtime_awards.txt)
Вот этот файл, я изменил только CSXSQL_RANK_TIME на CSXSQL_RANK_SKILL

**Comment by serfreeman1337** [comment]
Только что проверил у себя, все работает, при CSXSQL_RANK_SKILL права будут выдаваться топ 3 игрокам по скиллу.

Дальнейшие сообщения без каких либо логов или нужной информации буду игнорироваться.

**Comment by sashork** [comment]
Это всё да, но Когда включаю AES он не выдаёт вообще.
