### ISSUE TITLE
UFPS Admin Whois

### ISSUE THREAD

**Issue by patrig** [serfreeman1337/csstatsx-sql#4]
Использую у себя на сервере плагин от **UFPS** под названием: **Admin Whois**

О плагине: **Предназначен для удобного сбора и отображения информации о клинетах на сервере** - так же он выводит текущую позицию игрока ...

Выводится она таким образом:
```
case 'i':	//	Rank
		{
			new rank[8], nrank

			if ( !is_user_bot ( player ) && cvar_exists ( "csstats_reset" ) )
				nrank = get_user_stats ( player, rank, rank )
			else
				nrank = 0

			num_to_str ( nrank, rank, charsmax ( rank ) )

			formatex ( html, charsmax ( html ), "<TD>%s", rank )
		}
```

Поменял под CSS SQL:
```
case 'i':	//	Rank
		{
			new rank[8], nrank

			if ( !is_user_bot ( player ) /*&& cvar_exists ( "csstats_reset" ) */)
				nrank = get_user_stats_sql ( player, rank, rank )
			else
				nrank = 0

			num_to_str ( nrank, rank, charsmax ( rank ) )

			formatex ( html, charsmax ( html ), "<TD>%s", rank )
		}
```
Начиная с версии 0.7.2 = данная информация просто перестала отображаться, вывода информации вообще нет. На более ранних версиях все работало на ура.

Именно с версии 0.7.2 все и отвалилось ...

Как можно решить данную ... ?

**Comment by serfreeman1337** [comment]
Полный исходник это UFPS Admin Whois прикрепи.
Я ничего не делал в 0.7.2 с get_user_stats_sql.

**Comment by patrig** [comment]
@serfreeman1337, к сожалению я не могу прикрепить исходник данного плагина ибо это запрещено.

**Comment by serfreeman1337** [comment]
Ну тогда поддержка UFPS Admin Whois осуществляется только на DS ру.
